pipeline {
    agent any

    stages {
        stage ('Build') {
            steps {
                
                    sh "cd grupoA && docker build -t norte.0.0.${env.BUILD_ID} -f Dockerfile ."                
            }
        }

        stage ('Tag') {
            steps {

                    sh "cd grupoA && docker tag norte.0.0.${env.BUILD_ID} localhost:5000/norte.0.0.${env.BUILD_ID} && docker push localhost:5000/norte.0.0.${env.BUILD_ID}"
            }
        }

        stage ('Deploy') {
            steps {
               
                    sh "bash groupA/deploy.sh ${env.BUILD_ID}"               
            }
        }
    }
}
