name: ci

on:
  push:
   
jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
 
    env:
      TIME: $(date +%s)
      
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%s')"

      - name: Image build
        run: |-
          cd flask-app/
          docker build -t mativillagra/scratch:${{steps.date.outputs.date}} -f Dockerfile .

      - name: Image push 
        run: |-
          docker push mativillagra/scratch:${{steps.date.outputs.date}}

